name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: your-ecr-repo-uri:latest
          cache-from: type=registry,ref=your-ecr-repo-uri:cache
          cache-to: type=registry,ref=your-ecr-repo-uri:cache,mode=max

      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: your-lambda-function-name
          image-uri: your-ecr-repo-uri:latest
          region: your-aws-region
o	Asegúrate de reemplazar your-ecr-repo
